search:
    SliderBundle\Entity\Slider:
        alias:                          kiboko_slider
        title_fields:                   [name]
        route:
            name:                       kiboko_slider_view
            parameters:
                id:                     id
        search_template:                SliderBundle:Search:result.html.twig
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]