system_configuration:
    groups:
        slider_config:
            title: kiboko.slider.system_configuration.groups.slider_config.title
            icon: 'fa-picture-o'
        home_page:
            title: kiboko.slider.system_configuration.groups.home_page.title

    tree:
        system_configuration:
            commerce:
                children:
                    design:
                        children:
                            slider_config:
                                priority: 9000
                                children:
                                    home_page:
                                        children:
                                            - slider_bundle.use_cms_block
                                            - slider_bundle.slider
        website_configuration:
            commerce:
                children:
                    design:
                        children:
                            slider_config:
                                priority: 9000
                                children:
                                    home_page:
                                        children:
                                            - slider_bundle.use_cms_block
                                            - slider_bundle.slider
    fields:
        slider_bundle.use_cms_block:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: kiboko.slider.system_configuration.fields.use_cms_block.form_type.label
                tooltip: kiboko.slider.system_configuration.fields.use_cms_block.form_type.tooltip
                required: true
                constraints:
                    -   NotBlank: ~
        slider_bundle.slider:
            data_type: integer
            type: Symfony\Component\Form\Extension\Core\Type\IntegerType
            options:
                label: kiboko.slider.system_configuration.fields.slider.label
                required: true
                constraints:
                    -   NotBlank: ~
